[package]
name = "asmgen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.4.2"
env_logger = "0.11.11"
libfuzzer-sys = "0.4"

[dependencies.asmgen]
path = ".."

[[bin]]
name = "roundtrip"
path = "fuzz_targets/roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "optimise_bitops"
path = "fuzz_targets/optimise_bitops.rs"
test = false
doc = false
bench = false
